
name: petfyco
description: PetfyCo app (rescate y adopción) - Flutter starter
publish_to: "none"
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.5.0
  image_picker: ^1.1.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  google_maps_flutter: ^2.9.0
  geolocator: ^10.1.1
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
