name: petfyco
description: PetfyCo app (rescate y adopción) - Flutter
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Backend
  supabase_flutter: ^2.6.0
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.8.1
  
  # HTTP
  dio: ^5.5.0
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.3
  
  # Maps
  google_maps_flutter: ^2.9.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Location
  geolocator: ^12.0.0
  
  # Utils
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  
  # Image Picker (NUEVO - para subir fotos)
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/images/
    - assets/logo/

# Splash Screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/petfyco_splash.png
  color_dark: "#0D1C2E"
  image_dark: assets/logo/petfyco_logo_full_dark.png
  android_12:
    color: "#FFFFFF"
    image: assets/logo/petfyco_splash.png
    color_dark: "#0D1C2E"
    image_dark: assets/logo/petfyco_logo_full_dark.png
  web: true
  android: true
  ios: true

# App Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/petfyco_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/logo/petfyco_icon.png
  web:
    generate: true
    image_path: assets/logo/petfyco_icon.png
    background_color: "#FFFFFF"
    theme_color: "#4FC3F7"
