name: build_and_deploy

on:
  push:
    branches: [ main ]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'
          channel: 'stable'
          cache: true

      # Si también compilas APK:
      - name: Set up Java (Android)
        if: ${{ false }} # pon true si vas a generar APK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - run: flutter --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Web
        run: flutter build web --no-wasm-dry-run
